data:
    !xunet.MSSEG2DataModule {
        data_properties: ~/MSSEG-2/dataset.json,
        spacing: [1.0, 1.0, 1.0],
        spatial_size: [128, 128, 128],
        num_patches: 1,
        num_splits: 5,
        split: 0,
        batch_size: 1,
        num_workers: 4,
        cache_num: 4,
        cache_rate: 1.0,
        seed: 42,
    }

task:
    - !xunet.SemanticSegmentation
    - network:
          - !xunet.UNet
          - in_channels: 2
            out_channels: 1
            spatial_dims: 3
            encoder_depth: [1, 1, 1, 1, 1]
            encoder_width: [32, 64, 128, 256, 512]
            strides: [1, 2, 2, 2, 2]
            decoder_depth: [1, 1, 1, 1]
            stem: [!nn.Conv3d , { kernel_size: 3, padding: 1, bias: False }]
            downsample: [!nn.Conv3d , { kernel_size: 2, bias: False }]
            upsample: [!nn.ConvTranspose3d , { kernel_size: 2 }]
            head: [!nn.Conv3d , { kernel_size: 1 }]
            num_deep_supr: 3
            block: !xunet.Same
                - - !xunet.BasicBlock
                  - conv: [!nn.Conv3d , { kernel_size: 3, padding: 1 }]
                    norm: [!nn.GroupNorm , [8]]
                    act: !nn.LeakyReLU
      inferer:
          !xunet.MSSEG2Inferer {
              spacing: [1.0, 1.0, 1.0],
              spatial_size: [128, 128, 128],
              overlap: 0.5,
              post: class,
          }
      loss:
          !xunet.DeepSuprLoss {
              loss: !monai.DiceFocalLoss ,
              include_background: True,
              sigmoid: True,
              squared_pred: True,
              gamma: 2,
          }
      metrics:
          dice:
              !xunet.DiceMetric {
                  include_background: True,
                  include_zero_masks: True,
              }
          hd:
              !xunet.HausdorffDistanceMetric {
                  include_background: True,
                  include_zero_masks: True,
                  percentile: 95,
              }
          sensitivity: !xunet.SensitivityMetric {}
          specificity: !xunet.SpecificityMetric {}
      optimizer:
          - !optim.AdamW
          - { lr: 0.0001, weight_decay: 0.01 }
      scheduler:
          - !xunet.WarmupCosineSchedule
          - { warmup_steps: 2000, total_steps: 100000 }
      scheduler_config:
          interval: step

training:
    max_steps: 100000
    max_epochs: 9223372036854775807
    gpus: 2
    num_nodes: 1
    accelerator: ddp
    check_val_every_n_epoch: 50
    callbacks:
        - !pl.LearningRateMonitor { logging_interval: step }
        - !pl.ModelCheckpoint { every_n_train_steps: 50 }
        - !xunet.SaveValResults {
              save_path: logs/msseg2/fold0/resunet/version_0/results.csv,
          }
    logger: !pl.TensorBoardLogger { save_dir: logs/msseg2/fold0, name: resunet }

test:
    checkpoint:
        checkpoint_path: logs/msseg2/fold0/resunet/version_0/checkpoints/epoch=6249-step=99999.ckpt
    inferer:
        !xunet.MSSEG2Inferer {
            spacing: [1.0, 1.0, 1.0],
            spatial_size: [128, 128, 128],
            overlap: 0.5,
            post: class,
            write_dir: logs/msseg2/fold0/resunet/version_0/predictions,
        }
